### PR TITLE
Remove displaying programs in irrelevant states

### LINKED ISSUE #69: Remove programs from 'Ongoing' tab after reaching 'COMPLETED' state
**Describe the bug**
When a program is completed, it should not be visible in the 'Ongoing' tab in the 'COMPLETED' & 'REMOVED' state in the homepage layout.

**Expected behavior**
Programs that have reached the 'COMPLETED' state should be removed from the view

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium
 - Version 67.0.3369.0

### PR DESCRIPTION
**Pull request by miluckshan-j**
## Purpose
The purpose of this PR is to fix #69  😏

## Goals
Remove displaying programs that have been completed in the ongoing programs tab

## Approach

- Checked the state of each program and used ternary operator to check whether it was in 'COMPLETED' or 'REMOVED' state and removed it from homepage view. 
- Also found and fixed the 'Add Program' button that was hidden and not conditionally rendered for a normal user which seemed like a security vulnerability.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Windows 10
Chromium Version 67.0.3369.0

### CODE REVIEW

**Review by anjula-sack — DISMISSED** [review]
Thank you! @miluckshan-j

File: src/scenes/Home/components/ActivePrograms/index.tsx [hunk 1]
```diff
@@ -39,70 +39,76 @@ function ActivePrograms() {
...
+                          href={`/program/${program.id}/mentor/apply`}
+                        >
+                          Apply as a mentor
+                        </Button>
+                      ) : (
+                        ''
+                      )}
+                      {program.state == 'MENTEE_APPLICATION' && !isUserAdmin ? (
+                        <Button type="primary" href={`/program/${program.id}`}>
+                          Apply as a mentee
```
Comment (Gimhan-minion) [inline src/scenes/Home/components/ActivePrograms/index.tsx]: Same in here too  :)

File: src/scenes/Home/components/ActivePrograms/index.tsx [hunk 2]
```diff
@@ -39,70 +39,76 @@ function ActivePrograms() {
...
+                        href={`/dashboard/${program.id}`}
+                      >
+                        Manage
+                      </Button>
+                      {program.state == 'MENTOR_APPLICATION' && !isUserAdmin ? (
+                        <Button
+                          type="primary"
+                          href={`/program/${program.id}/mentor/apply`}
+                        >
+                          Apply as a mentor
```
Comment (Gimhan-minion) [inline src/scenes/Home/components/ActivePrograms/index.tsx]: Shall we rename this as `Apply as mentor`? WDYT? @miluckshan-j  @anjula-sack

Comment (anjula-sack) [reply src/scenes/Home/components/ActivePrograms/index.tsx]: Yeah it's better 
We discussed to use it like that right?

Comment (miluckshan-j) [reply src/scenes/Home/components/ActivePrograms/index.tsx]: Alright. Will look into it. Thanks for pointing it out.

File: src/scenes/Home/components/ActivePrograms/index.tsx (hunk 1 above)
Comment (miluckshan-j) [reply src/scenes/Home/components/ActivePrograms/index.tsx]: Noted.

**Review by anjula-sack — APPROVED** [review]
Thank you! @miluckshan-j
