### PR TITLE
Change the required message in mentor application

### LINKED ISSUE #230: Mentor application required message is wrong
**Describe the bug**
Mentor application required message is wrong

**To Reproduce**
1. Go to mentor application
2. Click on submit
3. See error message

**Expected behavior**
- Change the error message

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Big Sur 11.5.4
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #230 

- Showing a descriptive message 

## Approach

- Changed the required message in mentor application

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: src/scenes/Home/scenes/EditMentorApplication/index.tsx [hunk 1]
```diff
@@ -126,15 +126,20 @@ function MentorApplication() {
...
                               </Title>
                               <Form.Item
-                                name={question.id.questionId}
+                                name={question.question.id}
                                 initialValue={question.response}
-                                rules={[{ required: true }]}
+                                rules={[
+                                  {
+                                    required: true,
+                                    message: 'Please answer the question',
```
Comment (Gravewalker666) [inline src/scenes/Home/scenes/EditMentorApplication/index.tsx]: shall we change this to something simple like "Required" or something

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]

File: src/scenes/Home/scenes/EditMentorApplication/index.tsx (hunk 1 above)
Comment (anjula-sack) [reply src/scenes/Home/scenes/EditMentorApplication/index.tsx]: Done

**Review by Gravewalker666 — APPROVED** [review]
Nice work @anjula-sack
