### PR TITLE
Render rejected by mentor name

### LINKED ISSUE #290: Rejected by mentor name does not render
**Describe the bug**
The rejected by mentor name does not render in manage mentee admin view

**Additional context**
Update the render function of the following piece of code to what's at the bottom
https://github.com/sef-global/scholarx-frontend/blob/9f544f16ec86b6d8fa41b212ace8d61262d479dc/src/scenes/Dashboard/scenes/ManageMentees/index.tsx#L352-L360
```ts
                 render={(rejectedBy: Mentor) => {
                    return (
                      rejectedBy.profile.firstName +
                      ' ' +
                      rejectedBy.profile.lastName
                    );
                  }}
```

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
## Purpose

The purpose of this PR is to fix #290 

## Goals

- Render the name of the mentor which reject the mentee.

## Approach

- Render the rejected mentor name in the `WILDCARD` state and the `ONGOING` state.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
- OS: macOS BigSur
- Browser: Safari 14.0.1
- IDE: IntelliJ IDEA

### CODE REVIEW

File: src/scenes/Dashboard/scenes/ManageMentees/index.tsx [hunk 1]
```diff
@@ -349,15 +349,20 @@ function ManageMentees() {
...
-                <Column
-                  title="Rejected By"
-                  dataIndex={'rejectedBy'}
-                  render={(rejectedBy: string) => {
-                    return rejectedBy;
-                  }}
-                />
-              )}
+              {program?.state === 'WILDCARD' ||
+                (program?.state === 'ONGOING' && (
```
Comment (Gravewalker666) [inline src/scenes/Dashboard/scenes/ManageMentees/index.tsx]:
```suggestion
              {(program?.state === 'WILDCARD' ||
                program?.state === 'ONGOING') && (
```

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]

**Review by Gravewalker666 — APPROVED** [review]
Thanks @kumuditha-udayanga
