### PR TITLE
Display Mentor Confirmation tag when user is null (Mentor Confirmation state)

### LINKED ISSUE #201: Display Mentor_Confirmation tag when user is null (Mentor_Confirmation state)
**Describe the bug**
- When the program state Mentor_Confirmation and the user isn't logged in, the relevant program card does show the 'Mentor_Confirmation period' tag.

**To Reproduce**
- Add a condition to display the tag when the user is null and the program state is `Mentor_Confirmation`.

**Expected behavior**
- Display 'Mentor Confirmation Period' tag when the program is in Mentor_Confirmation state and the user is null (not logged in)

**Screenshots**

Screenshot 2021-07-16 at 14 18 22

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Browser: Safari
 - Version: 14.0.1

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
## Purpose

The purpose of this PR is to fix #201

## Goals

- Display 'Mentor Confirmation Period' tag when the program is in Mentor Confirmation state and the user is null (not logged in)
## Approach

- Add a condition to display the tag when the user is null and the program state is `Mentor Confirmation`.

## Screenshots

Approved Mentor's View
- Mentee View
Screenshot 2021-07-16 at 14 26 40

- Mentor View
Screenshot 2021-07-16 at 14 19 42

- User View
Screenshot 2021-07-16 at 14 20 55

- User(not logged)
Screenshot 2021-07-16 at 14 18 22

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
OS: macOS BigSur
Browser: Safari 14.0.1
IDE: IntelliJ IDEA

### CODE REVIEW

File: src/scenes/Home/components/ActivePrograms/index.tsx [hunk 1]
```diff
@@ -190,9 +190,10 @@ function ActivePrograms() {
                       Mentee Selection Period
                     </Tag>
                   )}
-                  {program.state === 'MENTOR_CONFIRMATION' &&
-                  !isUserAdmin &&
-                  mentoringPrograms.length ? (
+                  {(program.state === 'MENTOR_CONFIRMATION' &&
+                    !isUserAdmin &&
+                    mentoringPrograms.length) ||
+                  (program.state === 'MENTOR_CONFIRMATION' && user == null) ? (
```
Comment (anjula-sack) [inline src/scenes/Home/components/ActivePrograms/index.tsx]: This can be simplified

**Review by anjula-sack — CHANGES_REQUESTED** [review]

**Review by anjula-sack — APPROVED** [review]
