### PR TITLE
Hide manage button in mentee-applcation state

### LINKED ISSUE #204: Prevent showing 'Manage' button to the mentor in "MENTEE_APPLICATION" state
**Describe the bug**
- MENTEE_APPLICATION period showing a manage button for mentors (in my programs) 

**To Reproduce**
- Add a condition to prevent showing the button.

**Expected behaviour**
- 'Manage' button shouldn't appear to mentors in the "MENTEE_APPLICATION" state.

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Browser : Safari
 - Version : 14.0.1

### PR DESCRIPTION
**Pull request by kumuditha-udayanga**
## Purpose

The purpose of this PR is to fix #204

## Goals

- Prevent displaying the "Manage" button to the mentor in the Mentee-application state.
## Approach

- Add a condition to the button, to hide the Manage button while in the 'Mentee Application' state.

## Screenshots

mentorCard

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
 
OS: macOS BigSur
Browser: Safari 14.0.1
IDE: IntelliJ IIDEA

### CODE REVIEW

File: src/scenes/Home/components/MentorPrograms/index.tsx [hunk 1]
```diff
@@ -156,8 +156,14 @@ function MentorPrograms() {
             <MentorProgramCard
               key={program.id}
               program={program}
-              href={`/mentor/program/${program.id}`}
-              buttonText={'Manage'}
+              href={
+                program.state !== 'MENTEE_APPLICATION'
```
Comment (anjula-sack) [inline src/scenes/Home/components/MentorPrograms/index.tsx]: The condition is correct but it's not in the correct place.
it should be applied to the button itself.

**Review by anjula-sack — CHANGES_REQUESTED** [review]

File: src/scenes/Home/components/MentorPrograms/components/MentorProgramCard/interfaces.ts [hunk 2]
```diff
@@ -5,4 +5,5 @@ export interface MentorProgramCardProps {
   href?: string;
   buttonText?: string;
   isRejected: boolean;
+  state: string;
```
Comment (anjula-sack) [inline src/scenes/Home/components/MentorPrograms/components/MentorProgramCard/interfaces.ts]: the state is a string but they are more like enums. so it should be 'MENTEE_SELECTION' | 'MENTOR_SELECTION' | ... like this

**Review by anjula-sack — CHANGES_REQUESTED** [review]

File: src/scenes/Home/components/MentorPrograms/components/MentorProgramCard/interfaces.ts [hunk 3]
```diff
@@ -5,4 +5,13 @@ export interface MentorProgramCardProps {
   href?: string;
   buttonText?: string;
   isRejected: boolean;
+  state:
+    | 'CREATED'
```
Comment (anjula-sack) [inline src/scenes/Home/components/MentorPrograms/components/MentorProgramCard/interfaces.ts:9]: Remove the first `|`

**Review by anjula-sack — APPROVED** [review]
Thank you! @kumuditha-udayanga
