### PR TITLE
Show my mentor button for mentees who have previously been mentors

### LINKED ISSUE #232: 'My mentor' button is not visible for mentees.
**Describe the bug**
- 'My mentor' button is not visible for mentees.

**To Reproduce**
1. Go to a program
2. Apply as a mentee
3. Wait until the mentor confirmation 
4. See the program card

**Expected behavior**
- 'My mentor' button needs to be visible

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Big Sur 11.5.4
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #232 

## Goals

- Making the mentor confirmation view accessible

## Approach

- Added a filter for the mentoring programs check

## Screenshots
image

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

File: src/scenes/Home/components/ActivePrograms/index.tsx [hunk 1]
```diff
@@ -207,14 +209,20 @@ function ActivePrograms() {
                   )}
                   {program.state === 'MENTOR_CONFIRMATION' &&
                   !isUserAdmin &&
-                  (mentoringPrograms.length || user === null) ? (
+                  (mentoringPrograms.filter(
+                    (mentoringProgram) => mentoringProgram.id === program.id
+                  ).length ||
+                    user === null) ? (
```
Comment (jayasanka-sack) [inline src/scenes/Home/components/ActivePrograms/index.tsx]: let's flip this. .filter is expensive than the null check

File: src/scenes/Home/components/ActivePrograms/index.tsx [hunk 2]
```diff
@@ -207,14 +209,20 @@ function ActivePrograms() {
                   )}
                   {program.state === 'MENTOR_CONFIRMATION' &&
                   !isUserAdmin &&
-                  (mentoringPrograms.length || user === null) ? (
+                  (mentoringPrograms.filter(
+                    (mentoringProgram) => mentoringProgram.id === program.id
```
Comment (jayasanka-sack) [inline src/scenes/Home/components/ActivePrograms/index.tsx]: we can use `==` instead pf `===` because we use typescript

File: src/scenes/Home/components/ActivePrograms/index.tsx [hunk 3]
```diff
@@ -181,7 +181,9 @@ function ActivePrograms() {
                         program.state === 'ONGOING') &&
                       !isUserAdmin &&
                       user != null &&
-                      !mentoringPrograms.length ? (
+                      !mentoringPrograms.filter(
+                        (mentoringProgram) => mentoringProgram.id == program.id
+                      ).length ? (
```
Comment (jayasanka-sack) [inline src/scenes/Home/components/ActivePrograms/index.tsx]: `montoringPrograms.some((mentoringProgram) => mentoringProgram.id == program.id)` returns true if a program exists

**Review by Gravewalker666 — APPROVED** [review]
Awesome work @anjula-sack
